#+TITLE: My favorite games of all time

* What Genres do I like?
- RPGs
- Old School FPSes

* What genres do I (generally) dislike?
- ARPGs
- RTS
- Stealth
- Roguelikes

* Adventure
1. Roadwarden
2. Night in the Woods
3. Northern Journey
4. Norco
5. Brothers: A Tale of Two Sons
6. The Darkside Detective
7. Day of the Tentacle
8. Mini Ninjas
9. Sludge Life
10. Paratopic
11. Milk inside a bag of milk inside a bag of milk
* Sandbox/Simulators
* Shooters
* Immersive Sims
1. Dark Messiah of Might and Magic
2. Arx Fatalis
3. Bioshok
4. Deus Ex
5. Dishonored
* Platformers
1. A Short Hike
2. Hollow Knight
3. VVVVVV
4. Thomas Was Alone
5. Limbo
* Puzzle
1. Donut County
2. Superliminal
3. Portal 1, 2 and Revolution
4. Frog Detective Series
* RPGs
* Strategy
1. Thronefall

Thronefall was a lovely surprise.

This low polygon game consists of a day-night cycle were you build your defenses during the day (by spending your only resource: coins!) and must defend your castle at night, to help you do so you have a variety of building choices at your disposal.

From towers to windmills, you must choose where to spend your precious gold coins each day. Certain buildings are practically useless against certain types of enemies, and these, in turn, will come flooding down from different entrances to the map, so building placement (these can only be placed in pre-defined points) plays a big role on your success.

Despite the seemingly simple graphics and gameplay, the game can be surprisingly hard, depending on the map, gamemode and (optional) modifiers.

* Survival
1. Subnautica
2. Terraria
3. The Long Dark
4. Subnautica: Below Zero
